[profile.default]
solc = "0.8.22"
optimizer = true
optimizer_runs = 500
evm_version = "cancun"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  "@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
  "solidity-bytes-utils/=lib/solidity-bytes-utils/" 
]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
eth_sepolia = "${RPC_ETH_SEPOLIA}"
op_sepolia  = "${RPC_OP_SEPOLIA}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
ink_mainnet = "${RPC_INK_MAINNET}"
eth_mainnet = "${RPC_ETH_MAINNET}"

[profile.mainnet]
dotenv = ".env.ink-eth-mainnet"